### ISSUE TITLE
Question: compatible Python 3?

### ISSUE THREAD

**Issue by GerardPaligot** [Helioscene/dry-rest-permissions#5]
Hi,

I'm a contributor of the French open source project Zeste de Savoir and we think to integrate this project but we have a question: is it compatible with Python 3 or not yet? 

Thanks in advance for your answer!

**Comment by dbkaplan** [comment]
Hi Gerard,

I have not fully adapted it for python 3 yet. I don't think it will take a ton of more work though. If you get to it you can always send me a pull request and I will review and merge it in.

**Comment by artragis** [comment]
Hi,

2to3 script just ask for compatibility modification such as removing `from __future__ import print_function`.

I ran tests on a python3 env et everything was good. I think you can use your tox script to generate 2 envs, one with py2 and one with py3 and then run test in those two envs.

**Comment by mkohram** [comment]
Hey,

Any progress on this?

Thanks

**Comment by dbkaplan** [comment]
Hi Gerard,
I don't have any bandwidth at the moment. You can submit a pull request and I will review if you need it sooner.

**Comment by artragis** [comment]
PR is done #10

**Comment by dbkaplan** [comment]
Thanks for the work artragis. I published a new version to pypi at version 0.1.3.
