### ISSUE TITLE
Expose a permissions endpoint

### ISSUE THREAD

**Issue by Seraf** [Helioscene/dry-rest-permissions#9]
Hello,

It should be a great feature to be able to edit permissions throught api for an admin user.
For example, be able to list which user/group has which permissions for each object on an endpoint.
Be able to add permissions for a user on an object.

What do you think about this ?

Thanks for your work :)

**Comment by dbkaplan** [comment]
Hi Seraf,

Thanks for the request. Unfortunately, what you are asking is against the goal of this permissions package. What you are looking for are permissions defined by a permissions table (which is what django guardian does). This package was created to get around the limitations of having to explicitly assign permissions for every object. In doing that these permissions are defined by code that use existing relationship, so there is no way to change them in the admin tool.

With that being said you could have your permissions definitions look at django guardian tables as overrides.

**Comment by Seraf** [comment]
Hello,

Thanks, that make sense, sorry for the confusion
Regard.
